# ==========================================
# Application
# ==========================================
spring.application.name=config-server

# ==========================================
# Server
# ==========================================
server.port=8888

# ==========================================
# Config Server
# ==========================================
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///D:/ProdReadyProject/config-repo

# ==========================================
# Actuator
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ==========================================
# Logging
# ========================================== 
logging.level.root=INFO
logging.level.org.springframework.cloud.config=DEBUG